#!/bin/sh -xe

###
# Deploy to NPM
#
# The whole deployment process is as following
#   1. `npm version` which will create a new tag for deployment
#   2. `npm publish` which will push files to NPM and publish a new version
#   3. Push the new tag to GitHub
###

git config user.email "continuous.integration@intellihr.com.au"
git config user.name "IntelliHR CI"

echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc

npm version "$RELEASE_VERSION" -m "[ci skip] Upgrade to %s"
npm publish --access public

git remote add github "git@github.com:intellihr/recorder-js.git" || true
git push --tags github

git push github HEAD:master
